concurrency: 5
sumo:
  apiUrl: "https://api.eu.sumologic.com/api/v1/search/jobs"
  query:
    statement: '_source="kubernetes-proxy-public"'
    startDate: "2022-06-20T00:00:00"
    endDate: "2022-06-20T01:00:00"
    timeZone: "GMT"
filename: kuberenetes_proxy_public
s3:
  enabled: true
  bucket: adam-s3-upload-test
  deleteOnUpload: true

# Set as environment variables
ACCESS_ID: ""
ACCESS_KEY: ""
AWS_REGION: eu-west-1
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
